### PR TITLE
[meecast.spec] Fix typos in comments and changelog

### PR DESCRIPTION
**Pull request by Olf0**

### CODE REVIEW

**Comment by Olf0** [comment]
Sorry, was too tired to get this minimal fix right on first try: Please squash-merge.

**Comment by vasvlad** [comment]
Olf0, can I add your name as maintainer of rpm packaging?

**Comment by Olf0** [comment]
Sure, that is fine.
Side note: Initially I hesitated a bit to say "yes", because I perceive such a public attribution as a duty to really perform at least minimal maintenance, but I am aware that this is primarily my perception.  As you already experienced, sometimes I lack time for this task for multiple weeks.

Actually it is more than only the RPM packaging I do care about and plan to contribute in the future.  You may call it:
*Co-maintaining RPM packaging and project infrastructure (CI configuration, SailfishOS:Chum configuration etc.)*

------------------------------------------------------

Much more important is IMO to ensure continuity of MeeCast regardless of the availability of a single person: Any of us may be temporarily (due to private duties, illness etc.) or permanently (e.g. a fatal accident) unable to access this repository (not to mention the political turmoil this world is slipping into further and further, which already has some ugly, divisive effects on the FOSS ecosystem, e.g. barring some long time contributors and subsystem maintainers of Linux to continue their work).  The necessity to ensure continuity of MeeCast is exacerbated by the fact that Jolla's "Weather" app (by Foreca) ceased working more than a year ago and was ultimately removed in SailfishOS 4.6.0, hence MeeCast is the only weather forecast app with eventview widget for SailfishOS since then (and always has been the best generic weather forecast app for SailfishOS since MeeCast started supporting SailfishOS).

Consequently I would really appreciate if you invite me to [the GitHub-"organisation" `Meecast`](https://github.com/Meecast) using GitHub's web-frontend: https://github.com/orgs/Meecast/people
I already take care of the infrastructure maintenance at the GitHub-organisations [`sailfishos-chum`](https://github.com/orgs/sailfishos-chum/people), [`sailfishos-patches`](https://github.com/orgs/sailfishos-patches/people), [`storeman-developers`](https://github.com/orgs/storeman-developers/people) and [`sailfishos-applications`](https://github.com/orgs/sailfishos-applications/people), so the main developers can focus on coding (which I cannot for complex C++, QML, Python etc. code; I originally ceased coding in the 1990ties after having acquired some skills in writing C for microcontrollers and shell-scripts for UNIX at university, and before that BASIC and Pascal at high-school in the 1980ties).

**Comment by vasvlad** [comment]
I've sent to you an invitation  to the MeeCast Organization. Please check it.
And should I  use only your nickname (Olf0) or I can put your real name ( I don't know it) in AUTHORS information.

**Comment by Olf0** [comment]
> I've sent to you an invitation to the MeeCast Organization. Please check it.

Thank you.  Done, i.e. I accepted the invitation.

> And should I use only your nickname (Olf0) or I can put your real name ( I don't know it) in AUTHORS information.

For all my programming and SailfishOS-related work, I use simply "olf" as "real name".  "Olf0" is my account handle at GitHub and GitLab, because "olf" was already taken.

> P.S. See file AUTHORS

I suggest to simplify and shorten my entry in the AUTHORS file, see PR #73.

**Comment by Olf0** [comment]
> P.S.: Loosely related to both topics, collaborating and infrastructure: Please mind that [you have full access to MeeCast in the SailfishOS:Chum Testing OBS-repository](https://build.sailfishos.org/package/users/sailfishos:chum:testing/MeeCast). Hence, if you created a new MeeCast release at GitHub (and maybe after some testing of the binaries), can you please put the git-tag name of this release into [the `<revision>` parameter field in MeeCast's OBS service file](https://build.sailfishos.org/package/view_file/sailfishos:chum:testing/MeeCast/_service?expand=1) and click on the `Save` button in the toolbar of the mini-editor.

Thank you for doing that for `v1.11.8`.
Though I had the impression, that you missed to:
> Then switch to [MeeCast's "Overview" page there](https://build.sailfishos.org/package/show/sailfishos:chum:testing/MeeCast) and after MeeCast has been complied successfully for all targets, please use the `Submit package` button to submit this new release to `sailfishos:chum` (do leave all other fields empty). Thanks!

Thus I created [build.sailfishos.org/request/show/3556](https://build.sailfishos.org/request)./show/3556

You may wonder why I ask you do perform these steps, although I generally try to offload infrastructure work from you:
> Rationale: Currently there is usually a delay of many days between a new MeeCast release being available at OpenRepos and the SailfishOS:Chum community repository, because it takes a while for me to see that you created a new release. Hence IMO it is better, if you publish a new MeeCast release at both community repositories.

**Comment by vasvlad** [comment]
Ok. I forgot do this actions.

**Comment by Olf0** [comment]
> I forgot do this action.

Don't worry, I know it is a hassle to publish new releases for SailfishOS in two places.  Unfortunately both, OpenRepos and the SailfishOS:Chum community repository have their merits and drawbacks.  Originally I was hoped that SailfishOS:Chum would supersede OpenRepos, but that did not happen, some developers are using one, some the other and some both.  Personally I like  SailfishOS:Chum better, because it builds the packages from the source for each SailfishOS target release, but a target for SailfishOS 5.0.0 is still missing which is a regularly occurring drawback after each new SailfishOS release.

BTW, in hindsight most of [my advice WRT MeeCast-Eventview at OpenRepos](https://github.com/Meecast/meecast/issues/68#issuecomment-2468983962) was wrong, only that the original page should be kept at the original URL was valid.  I will provide more details and suggestions (hopefully proper ones, that time) when I have the time for that.

**Pull request merged**
